### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by patriot1889** [claudeheintz/LXNet2USBDMX#2]
The following files are missing;

CTNetUtilities.h
CTNetUtilities.m
WinTypes.h
usb.h
uDMX_cmds.h

Could you add them to the repository?

**Comment by claudeheintz** [comment]
The required utility functions have been added to CTUtility.h and CTUtility.m.
WinTypes.h and uDMX_cmds.h are included in the repo.
usb.h comes from libusb-compat (which is required for the project) and is not included.
You'll find usb.h in the source for libusb-compat at https://github.com/libusb/libusb-compat-0.1/tree/master/libusb
